### ISSUE TITLE
Next steps?

### ISSUE THREAD

**Issue by eddelbuettel** [jonclayden/RcppArray#2]
This looks really good now -- should it go to CRAN as is?   Or could it maybe be added to Rcpp?

**Comment by jonclayden** [comment]
I could send it to CRAN, but as it's pretty minimal I think it would be better to integrate it directly into `Rcpp`. Your call, of course, but I'm happy for it to be subsumed.

**Comment by eddelbuettel** [comment]
I am of two minds on this
- it would be 'cleaner' inside Rcpp, but it may also be harder as the package cleverly relies on some Rcpp features present
- the package system also works, and a simple LinkingTo can be a good first step; we would need a minimal change to move the header to `inst/include` which I could do in a quick PR

Somewhat as an aside, I also want to add `std::span` (for C++20 or later) but that may not be as urgent as C++20 is still little rare at CRAN. My dayjob work will move the C++ library I work with to C++20 come April.  But `span` suppport could of course also be its own header or package, or go to Rcpp the same way.

**Comment by eddelbuettel** [comment]
Ok, Rcpp 1.0.10 is now at CRAN so we have time to play til the next release :)   How about if I try to inject it, possibly towards the very end of the header list so that we can take advantage of earlier headers?   Adding `std::span` should then be a piece of cake.

**Comment by jonclayden** [comment]
OK, that's fine – I'm happy to wrangle this into a form suitable for `LinkingTo`, test it with a dummy client package and ship it to CRAN. Integration with core `Rcpp` would be great, but it can always follow later.

As for `span`, I'm not familiar with it, because none of my code uses a C++ standard recent enough, but I agree it would be nice to support it. If you think it belongs here I'd be happy to incorporate a PR, but I'm probably not best placed to write the implementation.

**Comment by jonclayden** [comment]
Oops, crossed comments. Either way is fine... :)

**Comment by eddelbuettel** [comment]
Hah!

One advantage of a new package is lighter reverse dependency tests as there aren't any :)  It's the CRAN way.

One advantage of inside Rcpp is that everybody gets it and I have been meaning to add some things for int64_t, more XPtr tools, maybe span one (we use in tiledb, currently via C++17 fill-in header, it seems to be one of those fancy modern c++ things but otherwise your stack-based Array appears interchangeable to me ...).

**Comment by jonclayden** [comment]
Alright, I will poke around over the next few days. It'll probably be educational, regardless! If you want to explore viability within `Rcpp` proper too, please feel free – I think universal `array` support at least would be great eventually, since it's from a now pretty old standard, and a bit of duplicated effort won't do me any harm. I'll post an update here before submitting anything to CRAN.

**Comment by jonclayden** [comment]
I now have [additional code which handles `span`](https://github.com/jonclayden/RcppArray/commit/e6cdb9c4e3556f15468ff4cd9cb16b3177e09ea0), and it compiles and appears to work from some initial experimentation. But I do wonder about the semantics. As I said, I don't use `span`, but my understanding is that it's a view that doesn't own the memory it points to, which makes me wonder whether `as<span<T,D>>(...)` makes any sense – particularly since any type conversion will leave you with a view into the converted data, which will be invalidated once the owning `Exporter` object is destroyed. `wrap` is much more straightforward, and seems like a pretty clean win.

**Comment by eddelbuettel** [comment]
Your rock, and good point.  I just got to seeing it in places as an API I wrap has it in a few interfaces.  Sometimes we just have a to create a `span` to get, or return, something.  But your warning is good (have to ponder this some more) and _at least_ something we can slab into the header.

**Comment by jonclayden** [comment]
The package seems to be `R CMD check` clean, and could probably go to CRAN. I've added simple client packages for `array` and `span` to check that linking against `RcppArray` works. There's another caveat around `as<span<T,D>>()`, though: I think it will only work for cases where `T` is a type that R uses as a native atomic type (viz. `int`, `double`, etc.). [Otherwise](https://github.com/jonclayden/RcppArray/blob/3e9ad626b41f21a8d32ca534cfd5bf205b214480/clients/span.test/src/main.cpp#L29) the code won't compile because the `span` specialisation doesn't match the type of the memory it's being pointed to. The resulting compile error isn't particularly clear, and could be a pain to support.

**Comment by eddelbuettel** [comment]
> to check that linking against `RcppArray` works.

Micro nit: That would be 'compiling' (or 'building') as it is really only header code, and the linker does not get involved.

Noted re the probable `span` limitation.  Maybe good enough for now to add a comment?

**Comment by jonclayden** [comment]
> Micro nit: That would be 'compiling' (or 'building') as it is really only header code, and the linker does not get involved.

Ah yes - true!

> Noted re the probable span limitation. Maybe good enough for now to add a comment?

OK, I’ll comment in the header, and add something to the README too.

**Comment by eddelbuettel** [comment]
Perfect -- I didn't even complete my sentence fully:  "a comment about it being experimental or explorative or preliminary ..." or something along those lines.  Buyer beware, standard open source warranty.  :wink:

**Comment by jonclayden** [comment]
BTW, the `span` client won’t build on the GitHub action I’m using for CI. It looks like the compiler doesn’t support C++20 (fully?) - does that ring any bells? I’d be surprised if ubuntu-latest didn’t have a new enough `gcc`…

**Comment by eddelbuettel** [comment]
Could be though we could switch between g++-11 and g++-12.  That is the trouble with the ifdefs.  I can take a peek later.

**Comment by eddelbuettel** [comment]
Just double checked:  Default under `ubuntu-latest` aka 22.04 is still g++-11 but there is g++-12 and we can call update-alternatives to make it the default.  I can fold that in.

(BTW when grep'ing here for an actions idiom recently I found your yaml file and absolutely loved it. First time I have seen 'by hand' parsing of DESCRIPTION to see what to install.  Excellent stuff.)

**Comment by eddelbuettel** [comment]
Also blows up on my 22.10 machine:

```sh
edd@rob:~/git/rcpparray/clients/span.test(main)$ install2.r -l /tmp/lib .
* installing *source* package ‘span.test’ ...
** using staged installation
** libs
ccache g++  -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include' -I'/usr/local/lib/R/site-library/RcppArray/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppExports.cpp -o RcppExports.o
ccache g++  -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include' -I'/usr/local/lib/R/site-library/RcppArray/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c main.cpp -o main.o
main.cpp:6:24: warning: missing terminating ' character
    6 | #error Span support isn't available
      |                        ^
main.cpp:6:2: error: #error Span support isn't available
    6 | #error Span support isn't available
      |  ^~~~~
main.cpp:9:60: error: ‘span’ in namespace ‘std’ does not name a template type
    9 | template <typename T, size_t D> void printSpan (const std::span<T,D> &sp) {
      |                                                            ^~~~
main.cpp:9:64: error: expected ‘,’ or ‘...’ before ‘<’ token
    9 | template <typename T, size_t D> void printSpan (const std::span<T,D> &sp) {
      |                                                                ^
main.cpp: In function ‘void printSpan(int)’:
main.cpp:11:22: error: ‘sp’ was not declared in this scope
   11 |   for (const T &el : sp)
      |                      ^~
main.cpp: In function ‘void foo(Rcpp::RObject)’:
main.cpp:18:8: error: ‘span’ is not a member of ‘std’
   18 |   std::span<int,3> s = Rcpp::as<std::span<int,3>>(x);
      |        ^~~~
main.cpp:18:13: error: expected primary-expression before ‘int’
   18 |   std::span<int,3> s = Rcpp::as<std::span<int,3>>(x);
      |             ^~~
main.cpp:19:13: error: ‘s’ was not declared in this scope
   19 |   printSpan(s);
      |             ^
main.cpp: In function ‘Rcpp::RObject bar()’:
main.cpp:25:8: error: ‘span’ is not a member of ‘std’
   25 |   std::span s(v.begin(), v.end());
      |        ^~~~
main.cpp:26:15: error: ‘s’ was not declared in this scope
   26 |   return wrap(s);
      |               ^
make: *** [/usr/lib/R/etc/Makeconf:178: main.o] Error 1
ERROR: compilation failed for package ‘span.test’
* removing ‘/tmp/lib/span.test’
Warning message:
In install.packages(pkgs, ...) :
  installation of package ‘.’ had non-zero exit status
edd@rob:~/git/rcpparray/clients/span.test(main)$ 
```

Maybe best to ... pause this test?

**Comment by eddelbuettel** [comment]
Ok if I do these  `#include <span>` before the include for RcppArray.h then it installs (and likely tests).

```sh
edd@rob:~/git/rcpparray/clients/span.test(main)$ install2.r -l /tmp/lib .
* installing *source* package ‘span.test’ ...
** using staged installation
** libs
ccache g++  -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include' -I'/usr/local/lib/R/site-library/RcppArray/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c RcppExports.cpp -o RcppExports.o
ccache g++  -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include' -I'/usr/local/lib/R/site-library/RcppArray/include'    -fpic  -g -O3 -Wall -pipe -pedantic -Wno-ignored-attributes  -c main.cpp -o main.o
ccache g++ -std=gnu++20 -Wl,-S -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o span.test.so RcppExports.o main.o -L/usr/lib/R/lib -lR
installing to /tmp/lib/00LOCK-span.test/00new/span.test/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  ‘span.test’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (span.test)
edd@rob:~/git/rcpparray/clients/span.test(main)$ 
```

**Comment by eddelbuettel** [comment]
(After a supper break)  

But now I don't quite understand why I needed it because

```c++
#if __cplusplus >= 202002L && defined(__cpp_lib_span)
#define HAVE_SPAN
#include <span>
#endif
```

looks as if it should have taken care of it.  Hm.

**Comment by jonclayden** [comment]
Yes, indeed – I guess the feature-test macros aren't reliable enough, so I'll try adding a `configure` script.

**Comment by eddelbuettel** [comment]
Those can indeed be the most solid. I have one or two that explicitly compile a test script and properly report back.  Here you likly only have to point `configure.ac` / `autoconf` at `span.h` (if and when you have a compiler candidate).

I don't really think I should impose all that work.  It was an idea :)   It will be easier one day.  But hey if you get it to work you can claim "supported `span` since 2023...."  :wink:

**Comment by jonclayden** [comment]
Sorted – I think we can claim that now. 😊

The package went to CRAN yesterday evening, and is now sitting in the newbies queue.

**Comment by jonclayden** [comment]
`RcppArray` is [now on CRAN](https://cran.r-project.org/package=RcppArray).
